[package]
name = "eveonau/framework"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Future = "red-blox/future@^1.0.0"
bytenet = "ffrostflame/bytenet@0.4.6"